language: php

sudo: false

services:
    - mysql

cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files
        - ./bin/.phpunit

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3

before-install:
    - composer self-update
#    - wget https://get.symfony.com/cli/installer -O - | bash
#    - sudo mv /home/travis/.symfony/bin/symfony /usr/local/bin/symfony

install:
    - composer install
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
    - php bin/console doctrine:fixtures:load -n --env=test

script:
    - ./bin/phpunit
    # this checks that the YAML config files contain no syntax errors
    - ./bin/console lint:yaml config --parse-tags
    # this checks that the Twig template files contain no syntax errors
    - ./bin/console lint:twig templates --env=prod
    # this checks that the XLIFF translations contain no syntax errors
    - ./bin/console lint:xliff translations
    # this checks that the application doesn't use dependencies with known security vulnerabilities
#    - symfony check:security
    # this checks that Doctrine's mapping configurations are valid
    - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction